# Azure DevOps Job deploying rp
parameters:
  environment: ''
  locations: []
  configFileName: ''
  azureDevOpsJSONSPN: ''
  vsoProjectID: ''
  vsoConfigPipelineID: ''
  vsoDeployerPipelineID: ''
  azureDevOpsE2EJSONSPN: ''
  e2eSubscription: ''

jobs:
- ${{ each location in  parameters.locations }}:
  - job: JustWait
    timeoutInMinutes: 300
    pool: server
    steps:
      - task: Delay@1
        inputs:
          delayForMinutes: '240'
  - job: Billing ${{ location }}_E2E
        variables:
          - template: ../vars.yml
        timeoutInMinutes: 480
        pool:
          vmImage: ubuntu-latest
        steps:
          - template: ./template-billing-e2e-steps.yml
            parameters:
              gobin: ${{ variables.GOBIN }}
              gopath: ${{ variables.GOPATH }}
              goroot: ${{ variables.GOROOT }}
              workingDirectory: ${{ variables.modulePath }}
              location: ${{ location }}
              subscription: ${{ parameters.e2eSubscription }}
              azureDevOpsE2EJSONSPN: ${{ parameters.azureDevOpsE2EJSONSPN }}
